import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import type { ResolvedDoc } from "./types.ts"

interface PathRule {
  from: string
  to: string
  status: string
}
interface LegacyRedirects {
  paths: PathRule[]
  wordpress: Record<string, string>
}

/** Loose key for matching slugs across punctuation/scheme drift (do-s ↔ dos). */
function looseKey(url: string): string {
  return url.toLowerCase().replace(/[^a-z0-9]/g, "")
}

export interface RedirectResult {
  redirectsFile: string
  functionFile: string
  pathCount: number
  pageCount: number
  wordpressCount: number
  remapped: string[]
  unresolved: string[]
}

/** Render the Cloudflare Pages Function handling legacy `/?p=NNN` WordPress redirects. */
function renderPFunction(pMap: Record<string, string>): string {
  return `// GENERATED by the ingest step — legacy WordPress ?p=NNN redirects (§11).
// Cloudflare Pages _redirects cannot match query strings, so this Function 301s
// /?p=NNN to its (live-resolved) target; everything else falls through to /.
const P = ${JSON.stringify(pMap, null, 2)}

export const onRequest = async (context) => {
  const url = new URL(context.request.url)
  const p = url.searchParams.get('p')
  if (p && Object.prototype.hasOwnProperty.call(P, p)) {
    return Response.redirect(url.origin + P[p], 301)
  }
  return context.next()
}
`
}

/**
 * Emit redirects (§11), robots.txt + humans.txt (§4) at build time.
 * - Legacy path rules + WordPress targets are resolved against the live URL set:
 *   exact match → kept; else loose-key remap (repairs slug drift); else dropped
 *   and reported (manual-fix list).
 * - `/pageN` rules generated from the real page count (can't drift).
 */
export function emitRedirects(opts: {
  repoRoot: string
  publicDir: string
  legacyPath: string
  overridesPath?: string
  docs: ResolvedDoc[]
  blogPageCount: number
}): RedirectResult {
  const { repoRoot, publicDir, legacyPath, overridesPath, docs, blogPageCount } = opts

  // Manual remaps for stale targets whose slug changed (owner-editable).
  const overrides: Record<string, string> =
    overridesPath && existsSync(overridesPath)
      ? JSON.parse(readFileSync(overridesPath, "utf8"))
      : {}

  // Live internal URL set + loose-key index. Includes custom routes that aren't
  // docs entries: the homepage, the /notes landing, and the category indexes.
  const liveUrls = new Set<string>(docs.map((d) => (d.url === "/notes/index" ? "/notes" : d.url)))
  liveUrls.add("/")
  liveUrls.add("/notes")
  for (const c of ["personal", "howto/development", "howto/system-administration"]) {
    liveUrls.add(`/blog/category/${c}`)
  }
  const byLoose = new Map<string, string>()
  for (const u of liveUrls) byLoose.set(looseKey(u), u)

  const remapped: string[] = []
  const unresolved: string[] = []

  /** Resolve an internal target to a live URL, or null if it can't be found. */
  function resolve(to: string): string | null {
    if (/^https?:\/\//i.test(to)) return to // external/splat — leave as-is
    const path = to.split(/[#?]/)[0]
    if (liveUrls.has(path)) return to
    if (overrides[path] && path !== "_comment") {
      const target = overrides[path]
      if (liveUrls.has(target)) return to.replace(path, target)
    }
    const hit = byLoose.get(looseKey(path))
    if (hit) {
      if (hit !== path) remapped.push(`${path} → ${hit}`)
      return to.replace(path, hit)
    }
    unresolved.push(to)
    return null
  }

  const legacy: LegacyRedirects = existsSync(legacyPath)
    ? JSON.parse(readFileSync(legacyPath, "utf8"))
    : { paths: [], wordpress: {} }

  // --- _redirects --- (Cloudflare: static rules must precede dynamic splats)
  const staticLines: string[] = []
  const splatLines: string[] = []
  for (const r of legacy.paths) {
    const to = resolve(r.to)
    if (to === null)
      continue // dropped (reported); never emit a redirect to a 404
    ;(r.from.includes("*") ? splatLines : staticLines).push(`${r.from} ${to} ${r.status}`)
  }
  // /pageN legacy URLs → clean /pageN, generated from the real page count.
  const pageLines: string[] = []
  for (let n = 2; n <= blogPageCount; n++) {
    pageLines.push(`/page${n}/index.html /page${n} 301`)
    pageLines.push(`/page${n}/ /page${n} 301`)
  }

  const lines: string[] = [
    "# GENERATED by ingest (§11). Targets in no-slash canonical form (D1).",
    ...staticLines,
    "# Paginated blog index (generated from page count):",
    ...pageLines,
    "# Host/apex splats (dynamic) last:",
    ...splatLines,
  ]

  const redirectsFile = join(publicDir, "_redirects")
  mkdirSync(dirname(redirectsFile), { recursive: true })
  writeFileSync(redirectsFile, lines.join("\n") + "\n", "utf8")

  // --- WordPress ?p=NNN Pages Function (resolved targets) ---
  const pMap: Record<string, string> = {}
  for (const [p, to] of Object.entries(legacy.wordpress)) {
    const resolved = resolve(to)
    if (resolved !== null) pMap[p] = resolved
  }
  const functionFile = join(repoRoot, "functions/index.ts")
  mkdirSync(dirname(functionFile), { recursive: true })
  writeFileSync(functionFile, renderPFunction(pMap), "utf8")

  return {
    redirectsFile,
    functionFile,
    pathCount: lines.filter((l) => !l.startsWith("#") && !l.includes("/page")).length,
    pageCount: blogPageCount,
    wordpressCount: Object.keys(pMap).length,
    remapped,
    unresolved,
  }
}

/** Emit Cloudflare Pages headers, robots.txt + humans.txt (§4). */
export function emitAuxFiles(publicDir: string, site: string): void {
  mkdirSync(publicDir, { recursive: true })
  const origin = site.replace(/\/$/, "")
  writeFileSync(
    join(publicDir, "_headers"),
    [
      "# Cloudflare Pages: prevent project and preview pages.dev URLs from being indexed.",
      "https://:project.pages.dev/*",
      "  X-Robots-Tag: noindex",
      "",
      "https://:version.:project.pages.dev/*",
      "  X-Robots-Tag: noindex",
      "",
    ].join("\n"),
    "utf8",
  )
  writeFileSync(
    join(publicDir, "robots.txt"),
    `User-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap-index.xml\n`,
    "utf8",
  )
  writeFileSync(
    join(publicDir, "humans.txt"),
    `/* TEAM */\nAuthor: Claus Conrad\nSite: ${origin}\n\n/* SITE */\nStandards: HTML5, CSS3\nComponents: Astro, Starlight\n`,
    "utf8",
  )
}
