name: Build www.clausconrad.com

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out build scripts
        uses: actions/checkout@v3

      - name: Check out blog
        uses: actions/checkout@v3
        with:
          repository: cconrad/cconrad.github.io
          token: ${{ secrets.GITHUB_PAT_READ_CCONRAD_GITHUB_IO }}
          path: cconrad.github.io

      - name: Check out notes
        uses: actions/checkout@v3
        with:
          repository: cconrad/dendron-personal
          token: ${{ secrets.GITHUB_PAT_READ_DENDRON_PERSONAL }}
          path: dendron-personal

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install node dependencies
        working-directory: ./cconrad.github.io
        run: npm install

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Build notes
        run: python3.11 build-pkm.py

      - name: Build blog
        working-directory: ./cconrad.github.io
        run: npm run build

      - name: Deploy to Netlify
        run: netlify deploy --dir cconrad.github.io/_site --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }} --build false --message "Deployed from GitHub Actions"
