name: Build www.clausconrad.com

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out build scripts
        uses: actions/checkout@v3
        with:
          repository: cconrad/www.clausconrad.com
          token: ${{ secrets.GITHUB_PAT_READ_WWW_CLAUSCONRAD_COM }}

      - name: Check out blog
        uses: actions/checkout@v3
        with:
          repository: cconrad/cconrad.github.io
          ref: notes
          token: ${{ secrets.GITHUB_PAT_READ_CCONRAD_GITHUB_IO }}
          path: cconrad.github.io

      - name: Check out notes
        uses: actions/checkout@v3
        with:
          repository: cconrad/dendron-personal
          token: ${{ secrets.GITHUB_PAT_READ_DENDRON_PERSONAL }}
          path: dendron-personal

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install node dependencies
        working-directory: ./cconrad.github.io
        run: npm install

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Build notes
        run: python3.11 build-pkm.py

      - name: Build blog
        working-directory: ./cconrad.github.io
        run: npm run build

      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: aa60a07a-5121-4633-84ed-b87148d5db84
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
          BUILD_DIRECTORY: cconrad.github.io/_site
          INSTALL_COMMAND: "echo Skipping installing the dependencies (pre-built on GitHub)"
          BUILD_COMMAND: "echo Skipping building the web files (pre-built on GitHub)"
